
	const cardWraper = document.querySelector(".cards")
	const costSelector = document.querySelector(".select-box-cost");
	
	let products = [
	{
		id: 0,
		name: "ручка дверная",
		model: "L422WH",
		old-price: 400,
		price: 355,
		interactive:
	}
	
	{
		id: 1,
		name: "ручка дверная",
		model: "L422WH",
		old-price: 400,
		price:355;
		interactive:
	}
	
	{
		id: 2,
		model: , 
		price: 
		interactive:
	}
	
	{
		id: 3,
		model:
		price:
		interactive:
	}
	
	{
		id: 4,
		model:
		price:
		interactive:
	}
	
	{
		id: 5,
		model:
		price:
		interactive:
	}
	
	{
		id: 6,
		model:
		price:
		interactive:
	}
	
	{
		id: 7,
		model:
		price:
		interactive:
	}
	
	{
		id: 8,
		model:
		price:
		interactive:
	}
	
	{
		id: 9,
		model:
		price:
		interactive:
	}
	
	{
		id: 10,
		model:
		price:
		interactive:
	}
	
	{
		id: 11,
		model:
		price:
		interactive:
	}
	
	]
	
	
	
	function render = () => {
		
		cardWraper.innerHTML = ""
		
	}
	
	render()